- name: install rime
  apt: 
    name: fcitx-rime
    state: latest
    update_cache: yes
  become: yes

- name: create rime config path
  file: path=~/.config/fcitx/rime/ state=directory recurse=yes
- name: copy rime config
  synchronize:
    src: .
    dest: ~/.config/fcitx/rime/
    delete: yes