- file: path="{{ install_dir }}" state=directory recurse=yes

- name: download golang to {{ install_dir }}/go
  unarchive:
    src: 'https://go.dev/dl/go{{ golang_version }}.linux-amd64.tar.gz'
    dest: "{{ install_dir }}"
    remote_src: yes
  args:
    creates: "{{ install_dir }}/go"
  when: in_china != "yes"


- name: download golang to {{ install_dir }}/go
  unarchive:
    src: 'https://mirrors.ustc.edu.cn/golang/go{{ golang_version }}.linux-amd64.tar.gz'
    dest: "{{ install_dir }}"
    remote_src: yes
  args:
    creates: "{{ install_dir }}/go"
  when: in_china == "yes"

- name: 添加golang环境变量
  lineinfile:
    dest: '{{ ansible_env.HOME }}/.rc'
    line: '{{ item.line }}'
    state: present
    create: true
  with_items:
    - { line: "export PATH=$PATH:{{ install_dir }}/go/bin" }
  # when: ansible_user_shell ==  "/usr/bin/zsh"
