---
- name: ubuntu20_desktop_init
  hosts: ubuntu
  remote_user: ubuntu
  roles:
    - repository
    - system_config
    - fonts
    - openssh-server
    - git
    - { role: zsh, zsh_theme: powerlevel10k }
    - vim
    - python3
    - { role: nodejs, nodejs_version: v14.17.0 }
    - rime
