---
- name: ubuntu20_wsl_init
  hosts: localhost
  vars:
    ansible_connection: local  # 加上这个所有task都在本机执行

  roles:
    - repository
    - system_config
    - git
    - zsh
    - vim
    - python3
    - role: nodejs
      vars:
        nodejs_version: v14.17.0