---
- name: ubuntu20_desktop_init
  hosts: ubuntu
  remote_user: mint
  roles:
    - repository
    - system_config
    - fonts
    - openssh-server
    - git
    - zsh
    - vim
    - python3
    - { role: nodejs, nodejs_version: v14.17.0 }
    - rime
