---
- name: desktop_init
  hosts: localhost
  remote_user: iuxt

  pre_tasks:
    - debug:
        msg: "{{ ansible_kernel }}"
    - name: check wsl
      fail: msg="this playbook don't support wsl"
      when: 
        ( 'WSL' in ansible_kernel )
        or
        ( 'Microsoft' in ansible_kernel )

  roles:
    - system_config
    - openssh-server
    - git
    - vim
    - python3
    - { role: nodejs, nodejs_version: v16.16.0 }
    - { role: golang, golang_version: 1.17.5 }
    - { role: hugo, hugo_version: 0.101.0 }
    - docker
    - startup
