---
- file: path="{{ install_dir }}" state=directory recurse=yes

- name: install Typora 0.11.18 in China
  unarchive:
    remote_src: yes
    src: https://file.babudiu.com/f/w0ty/typora-0-11-18.tar.gz
    dest: "{{ install_dir }}"
    creates: "{{ install_dir }}/typora"

- file: path="{{ ansible_env.HOME }}/.local/share/applications" state=directory recurse=yes

- name: create Typora desktop icons
  template:
    src: "typora.desktop.j2"
    dest: "{{ ansible_env.HOME }}/.local/share/applications/typora.desktop"
