---
- name: change vim config
  blockinfile:
    path: /etc/vimrc
    marker: "\" Ansible vimrc Change {mark}"
    block: |
      set paste

- name: change git config
  copy:
    src: .gitconfig
    dest: /root/.gitconfig
    owner: root
    group: root
    mode: '0644'