customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Rime::SwitcherSettings"
  modified_time: "Sun Apr 25 11:51:40 2021"
  rime_version: 1.5.3
patch:
  "menu/page_size": 8
  schema_list:
    - {schema: double_pinyin_mspy}
    - {schema: luna_pinyin}
    - {schema: clover}