- name: install basic tools
  apt: 
    name: [ 'wget', 'screen', 'psmisc', 'curl', 'apt-file', 'unzip']
    state: latest
    update_cache: yes
  become: yes

# system lib
  apt: 
    name: [ 'libbz2-dev', 'libreadline-dev', 'libssl-dev', 'libsqlite3-dev']
    state: latest
    update_cache: yes
  become: yes

- name: ulimit change
  blockinfile:
    path: /etc/security/limits.conf
    marker: "# Ansible limit Change {mark}"
    block: |
      *               soft    nofile          65535
      *               hard    nofile          65535
      *               hard    nproc           65535
      *               soft    nproc           65535
  become: yes

- name: change root passwd
  user: name=root password=$6$mL0N.2apkAYWJHsh$1MubHbuJ2.dMp421l2TMnXJj5ifMutyosAFcGtcG0jXSCshLH8o4l.JJlBdrg1ZXlerU8DV.hcHMyJtrM6xWC1
  become: yes
  # password generate by openssl passwd -6

# vmware workstation 点击挂起会卡死, 所以关闭挂起和休眠等功能.
- name: disable sleep.target suspend.target hibernate.target hybrid-sleep.target
  systemd:
    name: "{{ item }}"
    state: stopped
    enabled: no
    masked: yes
  become: yes
  with_items: 
    - "sleep.target"
    - "suspend.target"
    - "hibernate.target"
    - "hybrid-sleep.target"
  when: ansible_virtualization_type == "VMware"
