---
- hosts: localhost
  vars:
    ansible_connection: local  # 加上这个所有task都在本机执行
  # remote_user: root
  gather_facts: no
  tasks:

  - name: test
    file: path=/tmp/1 state=absent
    # delegate_to: localhost  # 加上这个这个task在本机执行

  - name: change chinese repo
    copy:
      src: files/sources.list
      dest: /etc/apt/
    become: yes
    # become_user: root  # 默认, 可以省
    # become_method: sudo  # 默认, 可以省

  - name: install some tools
    apt: 
      name: [ 'wget', 'screen', 'iotop', 'iftop', 'net-tools', 'vim', 'psmisc', 'curl' ]
      state: latest
      update_cache: yes
    become: yes

