---
- name: install vim
  apt: 
    name: ["vim", "vim-airline-themes"]
    state: latest
    update_cache: yes
  become: yes

- name: install vim plugin nerdtree
  git:
    repo: https://github.com/preservim/nerdtree.git
    dest: ~/.vim/pack/vendor/start/nerdtree

- name: change vim config
  copy:
    src: .vimrc
    dest: ~/.vimrc
