---
- name: mkdir ~/.local
  file: path=~/.local state=directory recurse=yes
- name: download nodejs to ~/.local
  unarchive:
    src: 'https://nodejs.org/dist/{{ nodejs_version }}/node-{{ nodejs_version }}-linux-x64.tar.xz' 
    dest: '~/.local/'
    remote_src: yes

- name: add path to .zshrc 
  lineinfile:
    dest: '~/.zshrc'
    line: '{{ item.line }}'
    state: present
    create: true
  loop:
    - { line: 'export PATH=$PATH:~/.local/node-{{ nodejs_version }}-linux-x64/bin' }

- name: change npm config
  copy:
    src: .npmrc
    dest: ~/.npmrc
