---
- name: download nodejs to /usr/local/
  unarchive:
    src: 'https://nodejs.org/dist/{{ nodejs_version }}/node-{{ nodejs_version }}-linux-x64.tar.xz'
    dest: '/usr/local/'
    remote_src: yes
  args:
    creates: /usr/local/node-{{ nodejs_version }}-linux-x64
  become: yes

- name: add path to .zshrc 
  lineinfile:
    dest: '~/.zshrc'
    line: '{{ item.line }}'
    state: present
    create: true
  loop:
    - { line: 'export PATH=$PATH:/usr/local/node-{{ nodejs_version }}-linux-x64/bin' }

- name: change npm config
  copy:
    src: .npmrc
    dest: ~/.npmrc
