# 更换主题为agnoster
- name: change zsh theme
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - { regexp: "^ZSH_THEME=.*",line: "ZSH_THEME=agnoster" }