
- name: 安装zsh和常用工具
  apt: 
    name: [ "zsh", "fzf" ]
    state: latest
    update_cache: no
  become: yes

- name: git clone oh-my-zsh
  git:
    repo: https://git.babudiu.com/mirror/ohmyzsh.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh"
    depth: 1

- name: copy .zshrc
  copy:
    src: "{{ ansible_env.HOME }}/.oh-my-zsh/templates/zshrc.zsh-template"
    dest: "{{ ansible_env.HOME }}/.zshrc"
    force: no

- name: change shell to zsh
  user: name={{ ansible_user_id }} shell=/usr/bin/zsh
  become: yes

- name: 创建个人用户bin目录
  ansible.builtin.file:
    path: "{{ ansible_env.HOME }}/.local/bin"
    state: directory
    recurse: yes

- name: zsh引用自定义rc文件,需要加在第一行
  ansible.builtin.lineinfile:
    path: "{{ ansible_env.HOME }}/.zshrc"
    line: "source ~/.rc"
    state: present
    insertbefore: '^# Enable Powerlevel10k instant prompt'
    create: true

# "{{ ansible_env.HOME }}/.local/bin is systemd default user binaries path , `systemd-path user-binaries`
- name: 增加.local/bin到自定义rc文件
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.rc"
    line: "export PATH=$PATH:{{ ansible_env.HOME }}/.local/bin"
    state: present
    create: true

- include: agnoster.yml
  when: zsh_theme == "agnoster"

- include: powerlevel10k.yml
  when: zsh_theme == "powerlevel10k"

- include: zsh-syntax-highlighting.yml
- include: zsh-autosuggestions.yml

- name: replace .zshrc plugin format
  replace:
    regexp: "^plugins=[(].*[)]"
    path: "{{ ansible_env.HOME }}/.zshrc"
    replace: |
      plugins=(
        z
        git
        sudo
        zsh-autosuggestions
        zsh-syntax-highlighting
        fzf
      )
