- name: git clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_env.HOME }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1

- name: add p10k config
  copy:
    src: .p10k.zsh
    dest: "{{ ansible_env.HOME }}/.p10k.zsh"

# 更换主题为powerlevel10k
- name: change zsh theme
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - { regexp: "^ZSH_THEME=.*",line: "ZSH_THEME=\"powerlevel10k/powerlevel10k\"" }

- name: add powerlevel10k config to "{{ ansible_env.HOME }}/.zshrc"
  lineinfile:
    dest: "{{ ansible_env.HOME }}/.zshrc"
    line: "[[ ! -f ~/.p10k.zsh ]] || source ~/.p10k.zsh"
    state: present