- name: git clone powerlevel10k
  git:
    repo: https://github.com/romkatv/powerlevel10k.git
    dest: "{{ ansible_user_id }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
  when: in_china != "yes"

- name: git clone powerlevel10k in China
  git:
    repo: https://e.coding.net/iuxt/github_mirror/powerlevel10k.git
    dest: "{{ ansible_user_id }}/.oh-my-zsh/custom/themes/powerlevel10k"
    depth: 1
  when: in_china == "yes"

- name: add p10k config
  copy:
    src: .p10k.zsh
    dest: "{{ ansible_user_id }}/.p10k.zsh"

# 更换主题为powerlevel10k
- name: change zsh theme
  lineinfile:
    dest: "{{ ansible_user_id }}/.zshrc"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
    state: present
  with_items:
  - { regexp: "^ZSH_THEME=.*",line: "ZSH_THEME=\"powerlevel10k/powerlevel10k\"" }

- name: add powerlevel10k config to "{{ ansible_user_id }}/.zshrc"
  lineinfile:
    dest: "{{ ansible_user_id }}/.zshrc"
    line: "[[ ! -f {{ ansible_user_id }}/.p10k.zsh ]] || source {{ ansible_user_id }}/.p10k.zsh"
    state: present