customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Weasel::UIStyleSettings"
  modified_time: "Sun Apr 25 11:52:08 2021"
  rime_version: 1.5.3
patch:
  "style/color_scheme": dark_temple
  "style/font_point": 22
  "style/horizontal": false
  us_keyboard_layout: true