---
- name: install python3
  apt: 
    name: ["python3", "python3-pip", "python3-gpg"]
    state: latest
    update_cache: no
  become: yes

- name: create link to python
  file:
    src: '/usr/bin/{{ item.src }}'
    dest: '/usr/bin/{{ item.dest }}'
    state: link
    force: yes
  with_items:
    - { src: python3, dest: python }
    - { src: pip3, dest: pip }
  become: yes

- file: path="{{ ansible_env.HOME }}/.config/pip/" state=directory recurse=yes
- name: change pip config
  copy:
    src: pip.conf
    dest: "{{ ansible_env.HOME }}/.config/pip/pip.conf"
