
- name: install zsh
  apt: 
    name: zsh
    state: latest
    update_cache: yes
  become: yes

- name: git clone oh-my-zsh
  git:
    repo: https://github.com/ohmyzsh/ohmyzsh.git
    dest: ~/.oh-my-zsh

- name: copy .zshrc
  copy:
    src: ~/.oh-my-zsh/templates/zshrc.zsh-template
    dest: ~/.zshrc
    force: no

- name: change shell to zsh
  user: name={{ ansible_user_id }} shell=/usr/bin/zsh
  become: yes

- name: create ~/.local/bin
  file: path=~/.local/bin state=directory recurse=yes

- name: add ~/.local/bin to ~/.zshrc
  lineinfile:
    dest: ~/.zshrc
    line: "export PATH=$PATH:~/.local/bin"
    state: present

- include: agnoster.yml
  when: zsh_theme == "agnoster"

- include: powerlevel10k.yml
  when: zsh_theme == "powerlevel10k"