customization:
  distribution_code_name: Weasel
  distribution_version: 0.14.3
  generator: "Rime::SwitcherSettings"
  modified_time: "Sun Apr 25 11:51:40 2021"
  rime_version: 1.5.3
patch:
  "menu/page_size": 8
  schema_list:
    - {schema: double_pinyin_mspy}
    - {schema: clover}
  switcher:
    caption: 张理坤
    hotkeys:
      - F4
  key_binder:
    bindings:
      - { when: paging, accept: bracketleft, send: Page_Up }
      - { when: has_menu, accept: bracketright, send: Page_Down }
