var:
  last_build_time: 1627620849
  option:
    ascii_punct: true
    simplification: false
  previously_selected_schema: double_pinyin_mspy
  schema_access_time:
    clover: 1627617619
    double_pinyin_mspy: 1627617698
    luna_pinyin: 1627615621