---
# tasks file for docker

- name: remove old version of docker
  apt: 
    name: ["docker", "docker-engine", "docker.io", "containerd", "runc"]
    state: absent
    update_cache: no
  become: yes

- name: install packages
  apt: 
    name: ["ca-certificates", "curl", "gnupg", "lsb-release"]
    state: latest
    update_cache: yes
  become: yes

# 用下面的 apt_key 模块更好
# - name: get file stat for gpg key
#   stat: path=/usr/share/keyrings/docker-archive-keyring.gpg
#   register: vscode_gpg_key

# - name: add gpg key
#   shell:
#     cmd: curl -fsSL https://download.docker.com/linux/ubuntu/gpg | gpg --dearmor -o /usr/share/keyrings/docker-archive-keyring.gpg
#   become: yes
#   when: not vscode_gpg_key.stat.exists

- name: 增加 docker 的 gpg key
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    keyring: /usr/share/keyrings/docker-archive-keyring.gpg
  become: yes

- name: 在Debian系统增加docker仓库
  template:
    src: docker-debian.list.j2
    dest: /etc/apt/sources.list.d/docker.list
  become: yes
  when: ansible_distribution == "Debian"

- name: add docker repo on ubuntu
  template:
    src: docker-ubuntu.list.j2
    dest: /etc/apt/sources.list.d/docker.list
  become: yes
  when: ansible_distribution == "Ubuntu"
  
- name: add docker repo on linux mint
  template:
    src: docker-linuxmint.list.j2
    dest: /etc/apt/sources.list.d/docker.list
  become: yes
  when: ansible_distribution == "Linux Mint"
  
- name: install docker via apt
  apt:
    name: ["docker-ce", "docker-ce-cli", "containerd.io"]
    state: latest
    update_cache: yes
  become: yes

- name: add current user to docker group
  user:
    name: "{{ ansible_user_id }}"
    groups: docker
    append: yes
  become: yes

- name: 创建docker配置文件目录
  file: path="/etc/docker" state=directory recurse=yes
  become: yes

- name: 复制docker配置文件
  copy:
    src: daemon.json
    dest: "/etc/docker/daemon.json"
  become: yes

- name: enable and start docker daemon
  systemd:
    name: "docker.service"
    state: started
    enabled: yes
  become: yes
