- name: install fcitx-rime
  apt: 
    name: [ 'fcitx-rime' ]
    state: present
    update_cache: no
  become: yes

- name: 创建fcitx-rime的配置文件目录
  file: 
    path: "{{ ansible_env.HOME }}/.local/share/fcitx/rime/"
    state: directory
    recurse: yes

- name: copy fcitx rime config
  synchronize:
    src: .
    dest: "{{ ansible_env.HOME }}/.local/share/fcitx/rime/"
    delete: yes
