- name: install fcitx5-rime
  apt: 
    name: [ 'fcitx5', 'fcitx5-rime' ]
    state: present
    update_cache: no
  become: yes

- name: 创建fcitx5-rime的配置文件目录
  file: 
    path: "{{ ansible_env.HOME }}/.local/share/fcitx5/rime/"
    state: directory
    recurse: yes

- name: copy fcitx5 rime config
  synchronize:
    src: config/
    dest: "{{ ansible_env.HOME }}/.local/share/fcitx5/rime/"
    delete: yes
