- name: remove fcitx5
  apt: 
    name:
    - fcitx5
    - fcitx5-rime
    - fcitx5-chinese-addons-data
    - fcitx5-module-chttrans 
    - fcitx5-module-fullwidth 
    - fcitx5-module-punctuation 
    - fcitx5-pinyin 
    - fcitx5-table

    state: absent
    update_cache: no
  become: yes

- name: install fcitx-rime
  apt: 
    name: [ 'fcitx-rime' ]
    state: present
    update_cache: no
  become: yes

- name: 创建fcitx-rime的配置文件目录
  file: 
    path: "{{ ansible_env.HOME }}/.config/fcitx/rime/"
    state: directory
    recurse: yes

- name: 检查是否已经存在rime配置
  stat:
    path: ~/.config/fcitx/rime/clover.userdb
  register: fcitx_userdb

- name: copy fcitx rime config
  synchronize:
    src: config
    dest: "{{ ansible_env.HOME }}/.config/fcitx/rime/"
    delete: yes
  when: not fcitx_userdb.stat.exists