- name: install ibus-rime
  apt: 
    name: [ 'fcitx5-rime' ]
    state: present
    update_cache: no
  become: yes

- name: 创建 ibus-rime 的配置文件目录
  file: 
    path: "{{ ansible_env.HOME }}/.config/ibus/rime"
    state: directory
    recurse: yes

- name: copy fcitx5 rime config
  synchronize:
    src: .
    dest: "{{ ansible_env.HOME }}/.config/ibus/rime/"
    delete: yes
