- name: 安装daemonize
  apt: 
    name: [ 'daemonize' ]
    state: present
    update_cache: no
  become: yes

# Linux Mint 20
- include: fcitx-rime.yml
  when: 
    - ansible_distribution == "Linux Mint"
    - ansible_distribution_major_version|int == 20

# Linux Mint 21
- include: fcitx-rime.yml
  when: 
    - ansible_distribution == "Linux Mint"
    - ansible_distribution_major_version|int == 21

# Debian
- include: fcitx5-rime.yml
  when: ansible_distribution == "Debian"

# Ubuntu 桌面版
- include: ibus-rime.yml
  when: 
    - ansible_distribution == "Ubuntu"
    - "'WSL2' not in ansible_kernel"

# WSL2
- include: fcitx5-rime.yml
  when: "'WSL2' in ansible_kernel"

- name: 创建.profile文件
  file:
    path: "{{ item }}"
    state: touch
    modification_time: preserve
    access_time: preserve
  with_items:
  - "~/.zprofile"
  - "~/.xprofile"

# 兼容wsl2启动输入法
- name: 兼容wsl2启动输入法
  blockinfile:
    block: |
      /usr/bin/fcitx5 --disable=wayland -d --verbose '*'=0

      export INPUT_METHOD=fcitx
      export GTK_IM_MODULE=fcitx
      export QT_IM_MODULE=fcitx
      export XMODIFIERS=@im=fcitx
      export SDL_IM_MODULE=fcitx
      export GLFW_IM_MODULE=ibus
    marker: "# {mark} rime autostart on wsl2 by ansible"
    path: "{{ item }}"
  become: no
  with_items:
  - "~/.zprofile"
  - "~/.xprofile"
  when: "'WSL2' in ansible_kernel"

# 复制wsl2的脚本
- name: 复制wsl2的脚本
  copy:
    src: tools/
    dest: "{{ ansible_env.HOME }}/"
    mode: 0755

# - name: create wayland environment
#   blockinfile:
#     block: |
#       INPUT_METHOD=fcitx
#       GTK_IM_MODULE=fcitx
#       QT_IM_MODULE=fcitx
#       XMODIFIERS=@im=fcitx
#     marker: "# {mark} fcitx auto start manage by ansible"
#     path: /etc/environment
#   become: yes
#   when: ansible_env.XDG_SESSION_TYPE == "wayland"
