- include: fcitx-rime.yml
  when: 
    - ansible_distribution == "Linux Mint"
    - ansible_distribution_major_version|int = 20

- include: fcitx5-rime.yml
  when: 
    ( ansible_distribution == "Linux Mint" and ansible_distribution_major_version|int = 21 )
    or
    ( ansible_distribution == "Debian" )

- include: ibus-rime.yml
  when: 
    ansible_distribution == "Ubuntu"

# - name: create wayland environment
#   blockinfile:
#     block: |
#       INPUT_METHOD=fcitx
#       GTK_IM_MODULE=fcitx
#       QT_IM_MODULE=fcitx
#       XMODIFIERS=@im=fcitx
#     marker: "# {mark} fcitx auto start manage by ansible"
#     path: /etc/environment
#   become: yes
#   when: ansible_env.XDG_SESSION_TYPE == "wayland"
